apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-devsecops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-devsecops
  template:
    metadata:
      labels:
        app: simple-devsecops
    spec:
      containers:
      - name: simple-devsecops
        image: dragz17/simple-devsecops
        ports:
        - containerPort: 5000
