apiVersion: v1
kind: Service
metadata:
  name: simple-devsecops-service
spec:
  type: NodePort
  selector:
    app: simple-devsecops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
